- hosts: all
  sudo: yes
  tasks:
      - name: Ensure {{ item }} is installed.
        apt: 
            pkg={{ item }}
            state=installed
        with_items:
            - git
            - vim
            - curl
            - build-essential
            - ocaml
            - libz-dev
            - i3
            - tmux

      - name: Clone node.js
        git: 
            repo=https://github.com/joyent/node
            dest=/tmp/node

      - name: Install node.js
        command: "{{ item }}"
        args:
            chdir: /tmp/node
        with_items:
            - ./configure
            - make
            - make install

      - name: Clone Haxe
        git: 
            repo=https://github.com/HaxeFoundation/haxe.git
            dest=/tmp/haxe
      
      - name: Install Haxe
        command: "{{ item }}"
        args:
          chdir: /tmp/haxe
        with_items:
            - make
            - make install


      - name: Download spf13 install script
        get_url: 
            dest=/tmp/spf13-vim.sh 
            url=https://j.mp/spf13-vim3
            validate_certs=no

      - name: Make spf13 script executable
        file:
          dest=/tmp/spf13-vim.sh
          mode="u=x"

      - name: install Spf13 for vim
        shell: "/tmp/spf13-vim.sh"



