- hosts: all
  sudo: yes
  tasks:
      - name: Ensure Git is installed.
        apt: pkg=git state=installed

      - name: Ensure Vim is installed.
        apt: pkg=vim state=installed

      - name: Ensure curl  is installed.
        apt: pkg=curl state=installed

      - name: Download spf13 install script
        get_url: 
            dest=/tmp/spf13-vim.sh 
            url=https://j.mp/spf13-vim3
            validate_certs=no

      - name: Make spf13 script executable
        file:
          dest=/tmp/spf13-vim.sh
          mode="u=x"

      - name: install Spf13 for vim
        shell: "/tmp/spf13-vim.sh"



